app            = "automation-eoineq"
primary_region = "den"

[build]          

[[services]]
  internal_port = 5678    
  protocol       = "tcp"

  [[services.ports]]
    port = 80               

  [[services.ports]]
    port = 443               
    handlers = ["tls", "http"]

[deploy]
  min_machines_running = 1

[[vm]]
  memory_mb = 1024
  cpu_kind  = "shared"
  cpus      = 1
