# ─────────────────────────────────────────────────────────
# fly.toml for self-hosted n8n (Automation-Eoineq)
# ─────────────────────────────────────────────────────────
app            = "automation-eoineq"
primary_region = "den"

[build]                      # ← leave empty; you’re using a Dockerfile

# ── Service definition (replaces old [http_service]) ──
[[services]]
  internal_port = 5678       # n8n listens on 5678
  protocol       = "tcp"

  [[services.ports]]
    port = 80                # HTTP

  [[services.ports]]
    port = 443               # HTTPS
    handlers = ["tls", "http"]

# ── Keep at least one machine running (no cold-start) ──
[deploy]
  min_machines_running = 1

# ── VM size ─────────────────────────────────────────────
[[vm]]
  memory_mb = 1024
  cpu_kind  = "shared"
  cpus      = 1
