# fly.toml app configuration file generated for automation-eoineq on 2025-06-25T20:09:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'automation-eoineq'
primary_region = 'den'

[build]

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'disabled'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
